---
# task file for nvim install
- name: dnf install nvim
  ansible.builtin.dnf:
    name: neovim
    state: latest

- name: Test if vimrc exists, fail if it does not
  ansible.builtin.file:
    path: "/home/perubu/Documents/Github/2.1.vim/1.Install/vimrc"
    state: file

- name: Ensure ~/.config/nvim/ exists
  ansible.builtin.file:
    path: /home/perubu/.config/nvim
    state: directory
    mode: "0755"
    group: perubu
    owner: perubu

- name: Create symbolic link for init.vim
  ansible.builtin.file:
    src: /home/perubu/Documents/Github/2.1.vim/1.Install/vimrc
    dest: /home/perubu/.config/nvim/init.vim
    state: link
    force: yes
