---
# task file for nvim install
- name: dnf install nvim
  ansible.builtin.package:
    name: neovim
    state: latest
  become: true

- name: Test if vimrc exists, fail if it does not
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/Documents/Github/2.1.vim/1.Install/vimrc"
    state: file

- name: Ensure ~/.config/nvim/ exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/nvim"
    state: directory
    mode: "0755"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

- name: Link init.vim for user
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/Documents/Github/2.1.vim/1.Install/vimrc"
    dest: "/home/{{ ansible_user }}/.config/nvim/init.vim"
    state: link
    force: yes

- name: Ensure directory exists
  ansible.builtin.file:
    path: /root/.config/nvim/
    state: directory
  become: true

- name: Link init.vim for superuser
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/Documents/Github/2.1.vim/1.Install/vimrc"
    dest: /root/.config/nvim/init.vim
    state: link
    force: yes
  become: true
