- name: dnf install nvim
  ansible.builtin.dnf:
    name: neovim
    state: latest

- name: Create ~/.config/nvim/ dir if it doesn't exist
  file:
    path: /home/perubu/.config/nvim
    state: directory
    mode: 0755
    group: perubu
    owner: perubu
    when: not directory_data.stat.exists

- name: Create symbolic link for init.vim
  file:
    src: /home/perubu/Documents/Github/2.1.vim/1.Install/vimrc
    dest: /home/perubu/.config/nvim/init.vim
    state: link
    force: yes
    when: not links.stat.exists
