---
# task file for nvim install
- name: dnf install nvim
  ansible.builtin.dnf:
    name: neovim
    state: latest
  become: true

- name: Test if vimrc exists, fail if it does not
  ansible.builtin.file:
    path: "/home/"{{ ansible_user }}"/Documents/Github/2.1.vim/1.Install/vimrc"
    state: file

- name: Ensure ~/.config/nvim/ exists
  ansible.builtin.file:
    path: /home/"{{ ansible_user }}"/.config/nvim
    state: directory
    mode: "0755"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

- name: Create symbolic link for init.vim
  ansible.builtin.file:
    src: /home/"{{ ansible_user }}"/Documents/Github/2.1.vim/1.Install/vimrc
    dest: /home/"{{ ansible_user }}"/.config/nvim/init.vim
    state: link
    force: yes
