---
# task file for webapps_install
- name: Ensure nodejs and npm are installed
  become: true
  ansible.builtin.dnf:
    name:
      - nodejs
      - npm
    state: latest

- name: Install nativefier globally
  become: true
  community.general.npm:
    name: nativefier
    global: yes
    state: latest

- name: Create Trello webapp
  vars:
    app_name: "Trello"
    webapp_url: "{{ trello_weblink }}"
    icon_path: "/home/perubu/.local/share/applications/icons/cnrtl.png"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}' --icon '{{ icon_path }}' '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

      