---
# task file for webapps_install
# Don´t use spaces in app_name , it will be used to create a directory, and then won't make the script idempotent
- name: Ensure nodejs and npm are installed
  become: true
  ansible.builtin.dnf:
    name:
      - nodejs
      - npm
    state: latest

- name: Install nativefier globally
  become: true
  community.general.npm:
    name: nativefier
    global: yes
    state: latest

- name: Create Cnrtl webapp
  vars:
    app_name: "Cnrtl"
    webapp_url: "https://cnrtl.fr/definition/"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}'  '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create Trello webapp
  vars:
    app_name: "Trello"
    webapp_url: "{{ trello_weblink }}"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}'  '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create le Conjugueur webapp
  vars:
    app_name: "le_Conjugueur"
    webapp_url: "https://leconjugueur.lefigaro.fr/"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}'  '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create WhatsApp webapp
  vars:
    app_name: "WhatsApp"
    webapp_url: "https://web.whatsapp.com/"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}'  '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create YouTube webapp
  vars:
    app_name: "YouTube"
    webapp_url: "https://youtube.com/"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}'  '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create Google search webapp
  vars:
    app_name: "GSearch"
    webapp_url: "https://www.google.com.hk/?hl=en-US&fg=1"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}' '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create Bing search webapp
  vars:
    app_name: "Bing_search"
    webapp_url: "https://www.bing.com/search?q=Bing+AI&showconv=1"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}' '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create Speedtest webapp
  vars:
    app_name: "Speedtest"
    webapp_url: "https://www.speedtest.net/"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}' '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create DeepAi chat
  vars:
    app_name: "DeepAi"
    webapp_url: "https://deepai.org/chat"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}' '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"

- name: Create Bard chat Wechat
  vars:
    app_name: "Bard"
    webapp_url: "https://bard.google.com/chat/3292a98e6af645e6"
  become: no
  shell:
    cmd: "cd ~/.local/bin && nativefier --name '{{ app_name }}' '{{ webapp_url }}' || exit"
    creates: "~/.local/bin/{{ app_name }}-linux-x64/{{ app_name }}"
