---
# task file for vim install
- name: dnf install vim-X11
  ansible.builtin.dnf:
    name: vim-X11
    state: latest
  become: true

- name: Test if vimrc exists, fail if it does not
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/Documents/Github/2.1.vim/1.Install/vimrc
    state: file

- name: Ensure ~/.vim/ exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.vim
    state: directory
    mode: "0755"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

# - name: Ensure directories exist, create if it does not
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: directory
#     mode: "0755"
#     group: "{{ ansible_user }}"
#     owner: "{{ ansible_user }}"
#   loop:
#     - /home/{{ ansible_user }}/.vim
#     - /home/{{ ansible_user }}/.vim/swap
#     - /home/{{ ansible_user }}/.vim/backup
#     - /home/{{ ansible_user }}/.vim/undo
#     - /home/{{ ansible_user }}/.vim/view

- name: Create symbolic link for vimrc
  ansible.builtin.file:
    src: /home/{{ ansible_user }}/Documents/Github/2.1.vim/1.Install/vimrc
    dest: /home/{{ ansible_user }}/.vim/vimrc
    state: link
    force: yes
