---
# task file for vim install
- name: dnf install vim-X11
  ansible.builtin.dnf:
    name: vim-X11
    state: latest

- name: Test if vimrc exists, fail if it does not
  ansible.builtin.file:
    path: "/home/perubu/Documents/Github/2.1.vim/1.Install/vimrc"
    state: file

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/perubu/.vim"
    - "/home/perubu/.vim/swap"
    - "/home/perubu/.vim/backup"
    - "/home/perubu/.vim/undo"
    - "/home/perubu/.vim/view"

- name: Create symbolic link for vimrc
  ansible.builtin.file:
    src: /home/perubu/Documents/Github/2.1.vim/1.Install/vimrc
    dest: /home/perubu/.vim/vimrc
    state: link
    force: yes
