---
# task file for vim install
- name: dnf install vim-X11
  ansible.builtin.dnf:
    name: vim-X11
    state: latest

- name: Ensure vimrc exists
  ansible.builtin.file:
    path: "/home/perubu/Documents/Github/2.1.vim/1.Install/vimrc"
    state: file

- name: Ensure .vim/ exists
  ansible.builtin.file:
    path: "/home/perubu/.vim"
    state: directory

- name: Check if init.vim exists
  ansible.builtin.stat:
    path: /home/perubu/.config/nvim/init.vim
  register: links

- name: Create symbolic link for init.vim
  ansible.builtin.file:
    src: /home/perubu/Documents/Github/2.1.vim/1.Install/vimrc
    dest: /home/perubu/.config/nvim/init.vim
    state: link
    force: yes
  when: not links.stat.exists

# test if will install link if link is broken