---
# inventories/hosts.yml
all:
  children:
    workstation:
      hosts:
        localhost:
          ansible_user: perubu
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    vms:
      hosts:
        192.168.122.133:
          ansible_user: perubu
          ansible_python_interpreter: /usr/bin/python3
