---
# tasks file to install google-chrome
- name: Install Third Party Repositories
  become: true
  ansible.builtin.package:
    name: fedora-workstation-repositories
    state: latest

- name: Enable the Google Chrome repo
  become: true
  command: dnf config-manager --set-enabled google-chrome
  args:
    creates: "/etc/yum.repos.d/google-chrome.repo"

- name: Install Google Chrome
  become: true
  ansible.builtin.package:
    name: google-chrome-stable
    state: latest
