---
# tasks file to install google-chrome
- name: Install Third Party Repositories
  become: yes
  ansible.builtin.dnf:
    name: fedora-workstation-repositories
    state: present
  become: true

- name: Enable the Google Chrome repo
  become: yes
  command: dnf config-manager --set-enabled google-chrome
  become: true

- name: Install Google Chrome
  become: yes
  ansible.builtin.dnf:
    name: google-chrome-stable
    state: present
  become: true
