---
# playbook.yml
- hosts: all
  become: true
  become_method: sudo
  roles:
    # - "libselinux_install"
    # - "config_dnf"
    # - "update_all_packages"
    # - "KDE_Plasma_install" if needed
    # - "boot_in_KDE" if needed
    - "vim_install"
    - "nvim_install"
    # - "vscode_install"
    # - "chrome_install"
