---
# playbook.yml
- hosts: all
  become: true
  become_method: sudo
  roles:
    # - "libselinux_install"
    # - "config_dnf"
    # - "update_all_packages"
    - "vim_install"
    - "nvim_install"
    # - "vscode_install"
    # - "chrome_install"
