---
# playbook.yml
- hosts: all
  become: true
  become_method: sudo
  roles:
    # - "python3_libselinux_install"
    # - "config_dnf"
    # - "update_all_packages"
    # - "ibus_chinese_ime"
    # - "vim_install"
    # - "nvim_install"
    # - "vscode_install"
    # - "chrome_install"
    - "brave_install"
