---
# playbook.yml
- hosts: all
  become: true
  become_method: sudo
  roles:
    # - "install_python3-libselinux"
    # - "config_dnf"
    # - "update_all_packages"
    # - "install_KDE_Plasma"
    # - "boot_in_KDE"
    - "vim_install" 
    # - "nvim_install" 
    # - "vscode_install"

