---
# playbook.yml
# run with:  $ ansible-playbook -i hosts playbook.yml --ask-vault-pass -K
# the local ansible.cfg file should contain the following lines
# [defaults]
# vault_password_file   = /tmp/.vault_pass.txt

# $ ansible-playbook -i hosts playbook.yml --ask-vault-pass -K

- hosts: all
  remote_user: "{{ ansible_user }}"
  become_method: sudo
  become: false # the only way for git_global_setup to work in regular user instead of root
  vars:
    vm_domain: "fedora41-cinnamon" # replace with your VM's domain name
  vars_files:
    # - /home/{{ansible_user}}/Documents/IHD_mimi/mimi_in_the_cloud/ansible_vault.yml
    # - /home/{{ansible_user}}/Documents/IHD_mimi/mimi_in_the_cloud/gh_mimi.yml
    # - /home/{{ansible_user}}/Documents/IHD_mimi/mimi_in_the_cloud/trello_mimi.yml
    - /run/media/{{ansible_user}}/USB_mimi/mimi_in_the_cloud/ansible_vault.yml
    - /run/media/{{ansible_user}}/USB_mimi/mimi_in_the_cloud/gh_mimi.yml
    - /run/media/{{ansible_user}}/USB_mimi/mimi_in_the_cloud/trello_mimi.yml
  roles:
    # some roles, not used here, are stored in roles_store
    - key_vault_pwd_setup

    - connect_to_a_vm
    - update_all_packages
    - snapper_install
    - dnf5_many_install
    - vim_install
    - nvim_install
    - bashrc_edit
    - vscode_install
    - brave_install
    - git_global_setup # requires become: false in the playing playbook
    - shellspec_install
    - anki_install # add ANKI_WAYLAND=1 in .bashrc
    - virtm_install
    - edge_install
    - webapps_install
    - startup_apps_setup
    - dot_bashrc_modif
    ######
    # - telegram_install
    # - foxit_reader_install
    # - chrome_install
    # - vlc_install
    # - speedtest_CLI_install
    # - debug
    # - test
    # - config_dnf
    # - system_settings # not idempotent
    # - ibus_chinese_ime  # CAREFUL, this will log out -- loosing all non saved data
