---
# playbook.yml
# run with:  $ ansible-playbook -Ki hosts playbook.yml --ask-vault-pass
# the local ansible.cfg file should contain the following lines
# [defaults]
# vault_password_file   = /tmp/.vault_pass.txt
- hosts: all
  remote_user: perubu
  become_method: sudo
  become: false # the only way for git_global_setup to work in regular user instead of root
  vars_files:
    - /mnt/TPad_mimi/mimi_in_the_cloud/ansible_vault.yml
    - /mnt/TPad_mimi/mimi_in_the_cloud/gh_mimi.yml
    - /mnt/TPad_mimi/mimi_in_the_cloud/trello_mimi.yml
    # - /run/media/perubu/USB_mimi/mimi_in_the_cloud/ansible_vault.yml
    # - /run/media/perubu/USB_mimi/mimi_in_the_cloud/gh_mimi.yml
    # - /run/media/perubu/USB_mimi/mimi_in_the_cloud/trello_mimi.yml
  roles:
    - key_vault_pwd_setup

    # - system_settings # not idempotent
    # # - ibus_chinese_ime  # CAREFUL, this will log out -- loosing all non saved data
    # - config_dnf
    # - update_all_packages
    # - snapper_install
    # - update_full_name
    # - dnf_many_install
    # - dot_bashrc_modif
    # - vim_install
    # - nvim_install
    # - speedtest_CLI_install
    # - vscode_install
    # - chrome_install
    # - brave_install
    # - vlc_install
    # - git_global_setup # requires become: false in the playing playbook
    # - shellspec_install
    # - webapps_install
    # - anki_install
    - speedtest_boot_run
    # - debug
    # - test
