---
# tasks file for config dnf

- name: Configure dnf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: "{{ item }}"
    state: present
  with_items:
    - "fastestmirror=true"
    # - "max_parallel_downloads=10"
  become: true
