---
# task file for virtm_install

- name: Install virt-manager
  become: true
  ansible.builtin.dnf:
    name: virt-manager
    state: latest

- name: Add user to libvirt group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: libvirt
    append: yes
      
# task file for dot_bashrc_modif
- name: Add export LIBVIRT_DEFAULT_URI to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: "export LIBVIRT_DEFAULT_URI=qemu:///system"
    state: present
