---
# task file for startup_apps_setup

- name: Define list of desktop entries
  set_fact:
    desktop_entries:
      - name: sys_monitor
        exec: "plasma-systemmonitor --page-name 'History' >/dev/null 2>&1"
        filename: "sys_monitor.desktop"
        comment: "Start System Monitor on login"
      - name: thunderbird_1.daily
        exec: "thunderbird -p '1.daily'"
        filename: "thunderbird_1.daily.desktop"
        comment: "Autostart Thunderbird (1.daily)"
      - name: thunderbird_2.google&yahoo
        exec: "thunderbird -p '2.google&yahoo'"
        filename: "thunderbird_2.google&yahoo.desktop"
        comment: "Autostart Thunderbird (2.google&yahoo)"
      - name: speedtest
        exec: "/home/"{{ ansible_user }}"/.local/bin/Test_my_speed-linux-x64/Test_my_speed"
        filename: "xyz.ketok.Speedtest.desktop"
        comment: "Autostart Speedtest"

- name: Check if file exists and create if not
  include_tasks: create_desktop_files.yml
  loop: "{{ desktop_entries }}"
  loop_control:
    loop_var: item
