---
# task file to create Speedtest.desktop
- name: Check if desktop file exists
  stat:
    path: /home/perubu/.config/autostart/xyz.ketok.Speedtest.desktop
  register: speedtest_desktop

- name: Ensure destination directory exists
  file:
    path: /home/perubu/.config/autostart/
    state: directory

- name: Create desktop file
  copy:
    content: |
      [Desktop Entry]
      Categories=GTK;
      Exec=/home/perubu/.local/bin/Test_my_speed-linux-x64/Test_my_speed
      Icon=xyz.ketok.Speedtest
      Name=Speedtest
      StartupNotify=true
      Terminal=false
      Type=Application
    dest: /home/perubu/.config/autostart/xyz.ketok.Speedtest.desktop
  when: speedtest_desktop.stat.exists == false
