---
- name: Set Task Switcher to 'informative' 1
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/kwinrc"
    values:
      - group: TabBox
        key: "LayoutName"
        value: "informative"

- name: Set shortcut for 'Walk through windows of current application' to Alt+T
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    values:
      - group: kwin
        key: "Walk Through Windows of Current Application"
        value: "Alt+T,Alt+`,Walk Through Windows of Current Application"

- name: Set shortcut for 'Walk through windows of current application (Reverse)' to Shift+Alt+T
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    values:
      - group: kwin
        key: "Walk Through Windows of Current Application (Reverse)"
        value: "Alt+Shift+T,Alt+~,Walk Through Windows of Current Application (Reverse)"
# - name: Reload KDE Plasma configuration 1
#   ansible.builtin.command: qdbus org.kde.KWin /KWin reconfigure

# - name: Reload KDE Plasma configuration 2
#   ansible.builtin.command: kquitapp5 plasmashell 2>/dev/null && kstart plasmashell 2>/dev/null && echo ok

# todo: Reload KDE Plasma configuration : none of the previous methods work, need to log out and log in again
