---
- name: Set Task Switcher to 'informative' 1
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/kwinrc"
    values:
      - group: TabBox
        key: "LayoutName"
        value: "informative"

- name: Set shortcut for 'Walk through windows of current application' to Alt+T
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    values:
      - group: kwin
        key: "Walk Through Windows of Current Application"
        value: "Alt+T,Alt+`,Walk Through Windows of Current Application"

- name: Set shortcut for 'Walk through windows of current application (Reverse)' to Shift+Alt+T
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    values:
      - group: kwin
        key: "Walk Through Windows of Current Application (Reverse)"
        value: "Alt+Shift+T,Alt+~,Walk Through Windows of Current Application (Reverse)"

- name: Settings / Personalization / Regional Settings / 1
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/KDE/Sonnet.conf"
    values:
      - { group: General, key: "defaultLanguage", value: "en_US" }
      - { group: General, key: "preferredLanguages", value: "en_US-w_accents, fr_FR", }

- name: Settings / Personalization / Regional Settings / 2
  community.general.kdeconfig:
    path: "{{ ansible_env.HOME }}/.config/plasma-localrc"
    values:
      - { group: Formats, key: LANG, value: "en_IE.UTF-8" }
      - { group: Formats, key: LC_DATE, value: "en_IE.UTF-8" }
      - { group: Formats, key: LC_TIME, value: "en_IE.UTF-8" }
      - { group: Formats, key: LC_MONETARY, value: "en_IE.UTF-8" }
      - { group: Formats, key: LC_CTYPE, value: "C.UTF-8" }
      - { group: Formats, key: LC_COLLATE, value: "C.UTF-8" }
      - { group: Formats, key: LC_MEASUREMENT, value: "C.UTF-8" }
      - { group: Formats, key: LC_NAME, value: "C.UTF-8" }
      - { group: Formats, key: LC_ADDRESS, value: "C.UTF-8" }
      - { group: Formats, key: LC_TELEPHONE, value: "C.UTF-8" }
      - { group: Formats, key: LC_PAPER, value: "C.UTF-8" }

- name: Reload KDE Plasma configuration 1
  ansible.builtin.command: qdbus org.kde.KWin /KWin reconfigure

- name: Quit kglobalaccel to apply changes
  ansible.builtin.command: kquitapp5 kglobalaccel
  ignore_errors: yes # kquitapp5 may fail if kglobalaccel is not running

- name: Restart kglobalaccel
  ansible.builtin.command: kglobalaccel5
  async: 10 # Run the task asynchronously
  poll: 0 # Fire and forget, don't wait for completion
