---
# tasks file to install dnf packages without having anything to set
# - name: dnf install multiple packages
#   become: true # now required since the playbook set it to false
#   ansible.builtin.dnf:
#     name:
#       - xclip # Todo: reinstall vim & nvim and check which clipboard mgr is installed
#       - htop # Todo: learn & update flashcard
#       - gparted
#       - gnome-disk-utility
#       - neofetch
#       - btrfs-assistant # Fedora only
#       - prename # Fedora only
#       - thunderbird
#       - ffmpeg
#       - hunspell-fr
#       - libreoffice-langpack-fr
#       - hyphen-fr
#       - libreoffice-grammalecte
#       - meld # for Gnome
#       - kompare # for KDE Plasma
#       - torbrowser-launcher.noarch
#       - numberstation
#       - filezilla
#       - wine
#       - wine.i686
#       - winetricks # required to install chinese fonts for WeChat
#       - cabextract # required to install chinese fonts for WeChat
#     state: latest

- name: Add  roootfind alias to ~/.bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    regexp: "^alias rootfind="
    line: "alias rootfind='sudo find / \\( -path \"/.snapshots\" -o -path \"/home/.snapshots\" -o -path \"/run\" \\) -prune -o '"
    state: present

- name: check if last line of .bashrc is empty
  shell: "[[ -z $(tail -n 1 /home/{{ ansible_user }}/.bashrc) ]]"
  register: result
  failed_when: false
  changed_when: false

- name: Append blank line to .bashrc if needed
  shell: "echo '' >>  /home/{{ ansible_user }}/.bashrc"
  when: result.rc != 0

- name: Add clear_GPUCache alias to ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    regexp: "^alias clear_GPUCache="
    line: alias clear_GPUCache='find ~/.config -type d -name GPUCache -exec rm -r {} \;'
    state: present

- name: check if last line of .bashrc is empty
  shell: "[[ -z $(tail -n 1 /home/{{ ansible_user }}/.bashrc) ]]"
  register: result
  failed_when: false
  changed_when: false

- name: Append blank line to .bashrc if needed
  shell: "echo '' >>  /home/{{ ansible_user }}/.bashrc"
  when: result.rc != 0

- name: Add VISUAL to ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    regexp: "^VISUAL="
    line: export VISUAL=nvim
    state: present

- name: check if last line of .bashrc is empty
  shell: "[[ -z $(tail -n 1 /home/{{ ansible_user }}/.bashrc) ]]"
  register: result
  failed_when: false
  changed_when: false

- name: Append blank line to .bashrc if needed
  shell: "echo '' >>  /home/{{ ansible_user }}/.bashrc"
  when: result.rc != 0

- name: Add EDITOR to ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    regexp: "^EDITOR="
    line: export EDITOR=nvim
    state: present

- name: check if last line of .bashrc is empty
  shell: "[[ -z $(tail -n 1 /home/{{ ansible_user }}/.bashrc) ]]"
  register: result
  failed_when: false
  changed_when: false

- name: Append blank line to .bashrc if needed
  shell: "echo '' >>  /home/{{ ansible_user }}/.bashrc"
  when: result.rc != 0
