---
# tasks file to install dnf packages without having anything to set
- name: dnf install multiple packages
  ansible.builtin.dnf:
    name:
      - xclip # Todo: reinstall vim & nvim and check which clipboard mgr is installed
      - htop # Todo: learn & update flashcard
      - gparted
      - gnome-disk-utility
      - neofetch
      - btrfs-assistant
    state: latest
