---
# tasks file to install dnf packages without having anything to set
- name: dnf install multiple packages
  become: true # now required since the playbook set it to false
  ansible.builtin.dnf:
    name:
      - xclip # Todo: reinstall vim & nvim and check which clipboard mgr is installed
      - htop # Todo: learn & update flashcard
      - gparted
      - gnome-disk-utility
      - neofetch
      - btrfs-assistant # Fedora only
      - prename # Fedora only
      - ffmpeg
      - hunspell-fr
      - libreoffice-langpack-fr
      - hyphen-fr
      - libreoffice-grammalecte
      - meld # for Gnome
      - kompare # for KDE Plasma
      - torbrowser-launcher.noarch
      - numberstation
      - filezilla
      - wine
      - wine.i686
      - winetricks # required to install chinese fonts for WeChat
      - cabextract # required to install chinese fonts for WeChat
    state: latest
