---
# task file for debug
# - name: Display github_username
#   debug:
#     msg: "{{ github_username }}"

# - name: Display github_email
#   debug:
#     msg: "{{ github_email }}"

- name: Display "{{ vault_password }}"
  debug:
    msg: "{{ vault_password }}"

- name: Display "{{ trello_weblink }}"
  debug:
    msg: "{{ trello_weblink }}"

- name: Register user - whoami_output
  command: whoami
  register: whoami_output
  become: false

- name: Display the current user -- whoami_output.stdout
  debug:
    var: whoami_output.stdout
  become: false

- name: Display "{{ ansible_env.HOME }}"
  debug:
    msg: "{{ ansible_env.HOME }}"

- name: Display ansible_user
  debug:
    # var: ansible_user
    msg: "{{ ansible_user }}"

# - name: Display vault_pass.txt
#   command: cat /tmp/.vault_pass.txt
#   register: vault_pass_txt

# - name: Display vault_pass_txt to console
#   debug:
#     msg: "{{vault_pass_txt.stdout}}"
#
# - name: Display environment variables
#   debug:
#     var: ansible_env
#   become: false
