---
- name: Install snapper
  ansible.builtin.package:
    name: snapper
    state: latest
  become: true

- name: Create snapshot of root
  command: snapper -c root create-config /
  args:
    creates: /.snapshots
  become: true

- name: Create snapshot of home
  command: snapper -c home create-config /home
  args:
    creates: /home/.snapshots
  become: true

- name: Ensure /etc/snapper/filters directory exists
  become: true
  file:
    path: /etc/snapper/filters
    state: directory
    mode: "0755"

- name: Create /etc/snapper/filters/excluded.txt
  become: true
  copy:
    dest: /etc/snapper/filters/excluded.txt
    content: |
      # files excluded for `snapper status <m>..<n>`

      # exclude log files
      /var/log/*

      # exlude Anki media files
      /home/"{{ ansible_user }}"/.local/share/Anki2/pj/collection.media/*

      # Exclude temporary files
      /tmp/*

      # Exclude cache files
      /home/"{{ ansible_user }}"/.cache/*

      #
    owner: root
    group: root
    mode: "0644"
