---
# task file for snapper_install

- name: Install snapper
  ansible.builtin.dnf:
    name: snapper
    state: latest

- name: Create snapper configuration for '/'
  command: snapper -c root create-config /
  args:
    creates: /etc/snapper/configs/root

- name: Create snapper configuration for '/home'
  command: snapper -c home create-config /home
  args:
    creates: /etc/snapper/configs/home

- name: Create snapshot for '/'
  command: snapper -c root create --description "Ansible snapshot"

- name: Create snapshot for '/home'
  command: snapper -c home create --description "Ansible snapshot"
