# task file for speedtest_install

- name: Install necessary packages
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - python-devel
    state: present

- name: Install Python package
  ansible.builtin.pip:
    name: aiohttp
    state: present

- name: Check if Ookla repository exists
  become: true
  ansible.builtin.stat:
    path: /etc/yum.repos.d/ookla_speedtest-cli.repo
  register: ookla_repo

- name: Add Ookla repository
  become: true
  ansible.builtin.shell: |
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.rpm.sh | bash
  when: ookla_repo.stat.exists == False

- name: Install speedtest
  become: true
  ansible.builtin.dnf:
    name: speedtest
    state: present

- name: Add alias to ~/.bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: "alias stest_speedtest='speedtest >/dev/null 2>&1 &'"
    state: present

# - name: check if last line of .bashrc is empty
#   shell: "[[ -z $(tail -n 1 /home/{{ ansible_user }}/.bashrc) ]]"
#   register: result
#   failed_when: false
#   changed_when: false

# - name: Append blank line to .bashrc if needed
#   shell: "echo '' >>  /home/{{ ansible_user }}/.bashrc"
#   when: result.rc != 0

- name: Check if .bashrc ends with a newline
  ansible.builtin.command: "tail -c 1 /home/{{ ansible_user }}/.bashrc"
  register: newline_check
  changed_when: false
  failed_when: false

- name: Ensure .bashrc ends with a newline
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: ''
    insertafter: EOF
  when: newline_check.stdout != ""
