- name: Configure Git with GitHub credentials
  ansible.builtin.git_config:
    scope: global
    name: user.name
    value: "{{ lookup('ansible.builtin.vault', 'secrets.yml --output=content')['github_username'] }}"
  become: true

- name: Configure Git with GitHub credentials
  ansible.builtin.git_config:
    scope: global
    name: user.email
    value: "{{ lookup('ansible.builtin.vault', 'secrets.yml --output=content')['github_email'] }}"
  become: true